# Generated by Django 3.2.4 on 2021-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image_site',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
