# Generated by Django 3.2.4 on 2021-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_account_image_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_site',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='images'),
        ),
    ]
